# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5905605134c8b47306ebc3dae84dc5623cf0edd29d9c6354c7ef9ce0d853938d184e4293f664a4b41c9ae0a40c6314a1232e50224a4b51c85c9a50bad1c47ddd

test:
  secret_key_base: 4c032c2e5ae0be5db845c0fd082bcb00880a41ac3b8714e0820284c17c478ff88dbe4e66b628669533936ba31341db1ae4e714412d1dc5b4e7df0939562d9bcb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
